import { Inter } from "next/font/google";
import "./globals.scss";
import NavBarCustom from "@/app/components/NavBarCustom";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Recipes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBarCustom />
        {children}
      </body>
    </html>
  );
}
