import { Inter } from "next/font/google";
import "./globals.scss";
import NavBarCustom from "@/app/components/NavBarCustom";
// import myImage2 from "../../public/bg2.jpg";
import myImage3 from "../../public/bg3.jpg";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Recipes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ backgroundImage: `url(${myImage3.src})` }}>
        <NavBarCustom />
        {children}
      </body>
    </html>
  );
}
